name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The target version you want to update and release'
        required: true
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upgrade the version number in the gradle.properties
        run: |
          sed -i "s|^\(version=\).*|\1${{ inputs.releaseVersion }}|" gradle.properties

      - name: Add tag and push to the repository
        run: |
          git config user.name "API Team"
          git config user.email "api-team@thousandeyes.com"

          git add .
          git commit -m "[GitHub Bot] Released ${{ inputs.releaseVersion }} SDK"
          git push origin

          git tag ${{ inputs.releaseVersion }}
          git push origin ${{ inputs.releaseVersion }}

      - name: Publish artifact
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY_BASE64 }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        run: |
          echo "New version: ${{ inputs.releaseVersion }}"
          echo "Github username: ${GITHUB_ACTOR}"
          gradle -Pversion=${{ inputs.releaseVersion }} publishMavenPublicationToMavenCentralRepository --parallel
