name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The target version you want to update and release'
        required: true
        type: string

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          # We need to use a PAT from an Admin user here, so that we can bypass the branch protection rules when pushing to main
          token: ${{ secrets.SDK_ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upgrade the version number in the gradle.properties
        run: |
          sed -i "s|^\(version=\).*|\1${{ inputs.releaseVersion }}|" gradle.properties

      - name: Add tag and push to the repository
        run: |
          git config user.name "API Team"
          git config user.email "api-team@thousandeyes.com"

          git add .
          git commit -m "[GitHub Bot] Released ${{ inputs.releaseVersion }} SDK"
          git push origin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.releaseVersion }}
          prerelease: false
          draft: false
          generate_release_notes: true

      - name: Publish artifact
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY_BASE64 }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        run: |
          echo "New version: ${{ inputs.releaseVersion }}"
          echo "Github username: ${GITHUB_ACTOR}"
          gradle -Pversion=${{ inputs.releaseVersion }} publishMavenPublicationToMavenCentralRepository --parallel
